// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhvlokknisipnzgrpudh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodmxva2tuaXNpcG56Z3JwdWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjA0NDgsImV4cCI6MjA2NjMzNjQ0OH0.YkVbSOhq7qB4GpXod2E6Bzpt6yu6CUwHL9VBfGWjM8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);